name: SL bug
description: Report incorrect SL Repo behavior
title: "SL bug: "
labels:
  - bug
body:
  - type: textarea
    id: behavior
    attributes:
      label: Observed behavior
    validations:
      required: true
  - type: textarea
    id: safety
    attributes:
      label: Was knowledge incorrectly activated, quarantined, or deleted?
    validations:
      required: true
