name: SL feature
description: Propose an SL Repo capability
title: "SL: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: Expected outcome
    validations:
      required: true
